package guessinggame;



import javax.swing.JOptionPane;


public class Dashboard extends javax.swing.JFrame {

    
   
    
    public Dashboard() {
       
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFrame = new javax.swing.JPanel();
        startBtn = new javax.swing.JButton();
        picLabel = new javax.swing.JLabel();
        highScoreBtn = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();
        creditBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard!");
        setMinimumSize(new java.awt.Dimension(493, 560));
        setName("dashboardFrame"); // NOI18N
        setResizable(false);

        bgFrame.setBackground(new java.awt.Color(43, 43, 43));
        bgFrame.setForeground(new java.awt.Color(255, 255, 255));
        bgFrame.setMaximumSize(new java.awt.Dimension(493, 560));
        bgFrame.setMinimumSize(new java.awt.Dimension(493, 560));

        startBtn.setBackground(new java.awt.Color(103, 125, 183));
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setText("Start playing!");
        startBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startBtn.setFocusable(false);
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        picLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guessinggame/start.png"))); // NOI18N

        highScoreBtn.setBackground(new java.awt.Color(103, 125, 183));
        highScoreBtn.setForeground(new java.awt.Color(255, 255, 255));
        highScoreBtn.setText("Highscore");
        highScoreBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        highScoreBtn.setFocusable(false);
        highScoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoreBtnActionPerformed(evt);
            }
        });

        msgLabel.setBackground(new java.awt.Color(0, 0, 0));
        msgLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 255, 255));
        msgLabel.setText("WELLCOME "+Player.getPlayerName()+" !");

        creditBtn.setBackground(new java.awt.Color(103, 125, 183));
        creditBtn.setForeground(new java.awt.Color(255, 255, 255));
        creditBtn.setText("Credit");
        creditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditBtn.setFocusable(false);
        creditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(158, 43, 37));
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setText("Log out!");
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn.setFocusable(false);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgFrameLayout = new javax.swing.GroupLayout(bgFrame);
        bgFrame.setLayout(bgFrameLayout);
        bgFrameLayout.setHorizontalGroup(
            bgFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgFrameLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(bgFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(highScoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picLabel)
                    .addComponent(msgLabel)
                    .addComponent(logOutBtn))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        bgFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {creditBtn, highScoreBtn, startBtn});

        bgFrameLayout.setVerticalGroup(
            bgFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgFrameLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(msgLabel)
                .addGap(18, 18, 18)
                .addComponent(picLabel)
                .addGap(33, 33, 33)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(highScoreBtn)
                .addGap(38, 38, 38)
                .addComponent(creditBtn)
                .addGap(18, 18, 18)
                .addComponent(logOutBtn)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        bgFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {creditBtn, highScoreBtn, startBtn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void creditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, """
            Our project is a mobile game called \"Guessing Game,\". 
            The game has two modes: guessing numbers and guessing alphabet letters.
            Our objective is to provide an engaging and challenging gaming experience that is suitable for all ages.
            Developed by:
            -Muhammad Suayb  :  (210-209-337)
            Major :
            B.Sc Software engineering

            Copyright c 2023 by Guessing Game developer.
            All rights reserved.
            https://www.linkedin.com/in/muhammedshoaib""");
    }//GEN-LAST:event_creditBtnActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        GameDashboard next=new GameDashboard();
        dispose();
        next.setVisible(true);
    }//GEN-LAST:event_startBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        SigninPage back=new SigninPage();
        dispose();
        back.setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    
    private void highScoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoreBtnActionPerformed
        // TODO add your handling code here:
        HighScore highscore=new HighScore();
        dispose();
        highscore.setVisible(true);
    }//GEN-LAST:event_highScoreBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgFrame;
    private javax.swing.JButton creditBtn;
    private javax.swing.JButton highScoreBtn;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel picLabel;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
