package guessinggame;



import java.awt.Color;


public class GameDashboard extends javax.swing.JFrame {
                         
    
    
    public GameDashboard() {
   
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFrame = new javax.swing.JPanel();
        Difficulty = new javax.swing.JComboBox<>();
        difficultyLabel = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        gameType = new javax.swing.JComboBox<>();
        modeLabel = new javax.swing.JLabel();
        picModeLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose a game!");
        setBackground(new Color(60,63,65));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(java.awt.Color.white);
        setResizable(false);

        bgFrame.setBackground(new java.awt.Color(43, 43, 43));
        bgFrame.setForeground(new java.awt.Color(255, 255, 255));
        bgFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bgFrame.setMaximumSize(new java.awt.Dimension(493, 560));
        bgFrame.setMinimumSize(new java.awt.Dimension(493, 560));
        bgFrame.setPreferredSize(new java.awt.Dimension(493, 560));

        Difficulty.setBackground(java.awt.Color.gray);
        Difficulty.setForeground(new java.awt.Color(255, 255, 255));
        Difficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));
        Difficulty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        difficultyLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        difficultyLabel.setForeground(new java.awt.Color(255, 255, 255));
        difficultyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        difficultyLabel.setLabelFor(Difficulty);
        difficultyLabel.setText("Choose Difficulty:");

        startBtn.setBackground(new java.awt.Color(158, 43, 37));
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setText("START");
        startBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        gameType.setBackground(java.awt.Color.gray);
        gameType.setForeground(new java.awt.Color(255, 255, 255));
        gameType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AlphaBet", "Number" }));
        gameType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gameType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameTypeActionPerformed(evt);
            }
        });

        modeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modeLabel.setForeground(new java.awt.Color(255, 255, 255));
        modeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modeLabel.setLabelFor(gameType);
        modeLabel.setText("Choose Mode:");

        picModeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guessinggame/mode.png"))); // NOI18N

        backBtn.setBackground(new java.awt.Color(158, 43, 37));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("back>");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgFrameLayout = new javax.swing.GroupLayout(bgFrame);
        bgFrame.setLayout(bgFrameLayout);
        bgFrameLayout.setHorizontalGroup(
            bgFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgFrameLayout.createSequentialGroup()
                .addGroup(bgFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgFrameLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(bgFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(gameType, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startBtn)
                            .addComponent(backBtn)))
                    .addGroup(bgFrameLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(modeLabel))
                    .addGroup(bgFrameLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(difficultyLabel))
                    .addGroup(bgFrameLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(picModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        bgFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Difficulty, gameType});

        bgFrameLayout.setVerticalGroup(
            bgFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgFrameLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(picModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(modeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameType, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(difficultyLabel)
                .addGap(2, 2, 2)
                .addComponent(Difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(startBtn)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        bgFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Difficulty, gameType});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gameTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameTypeActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
GameMode tempObject;
String userModeSelect=(String)gameType.getSelectedItem();
String userTypeSelect=(String)Difficulty.getSelectedItem();

    if(userModeSelect.contains("AlphaBet")){
                            tempObject=new AlphaMode(null);         
                        }else  {tempObject=new NumberMode(null);}
    
    if(userTypeSelect.contains("Easy"))
            tempObject.difficultyType=new EasyLevel();
    else if(userTypeSelect.contains("Medium"))
         tempObject.difficultyType=new MediumLevel();
    else  tempObject.difficultyType=new HardLevel();
    
        
       StartPlayingPage next=new StartPlayingPage();
       next.initReqData(tempObject);
           dispose();
           next.setVisible(true);
     
    }//GEN-LAST:event_startBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        Dashboard back=new Dashboard();
        dispose();
        back.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Difficulty;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bgFrame;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JComboBox<String> gameType;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JLabel picModeLabel;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
