/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guessinggame;


import java.sql.*;
/**
 *
 * @author SHADOWVY
 */
public class Welcome extends javax.swing.JFrame {
    

  
    Connection con= Database.dbconnect();
    PreparedStatement ps;
  
    ResultSet rset;
    
    public Welcome() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgWellcome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        signinBtn = new javax.swing.JButton();
        signupBtn = new javax.swing.JButton();
        wellcomePic = new javax.swing.JLabel();
        WellcomingMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setResizable(false);

        bgWellcome.setBackground(new java.awt.Color(43, 43, 43));
        bgWellcome.setForeground(new java.awt.Color(255, 255, 255));
        bgWellcome.setFocusable(false);
        bgWellcome.setPreferredSize(new java.awt.Dimension(493, 560));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        signinBtn.setBackground(new java.awt.Color(103, 125, 183));
        signinBtn.setForeground(new java.awt.Color(255, 255, 255));
        signinBtn.setText("Sign in!");
        signinBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signinBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signinBtn.setFocusable(false);
        signinBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinBtnActionPerformed(evt);
            }
        });

        signupBtn.setBackground(new java.awt.Color(158, 43, 37));
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("Sign up !");
        signupBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signupBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupBtn.setFocusable(false);
        signupBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        wellcomePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guessinggame/Welcomeimg.png"))); // NOI18N

        WellcomingMsg.setBackground(new java.awt.Color(255, 255, 255));
        WellcomingMsg.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        WellcomingMsg.setForeground(new java.awt.Color(255, 255, 255));
        WellcomingMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WellcomingMsg.setText("Wellcome to our guessing game!");

        javax.swing.GroupLayout bgWellcomeLayout = new javax.swing.GroupLayout(bgWellcome);
        bgWellcome.setLayout(bgWellcomeLayout);
        bgWellcomeLayout.setHorizontalGroup(
            bgWellcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgWellcomeLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(bgWellcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(signinBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(wellcomePic)
                    .addComponent(WellcomingMsg))
                .addGap(57, 57, 57))
            .addGroup(bgWellcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgWellcomeLayout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(120, 120, 120)))
        );
        bgWellcomeLayout.setVerticalGroup(
            bgWellcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgWellcomeLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(WellcomingMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(wellcomePic)
                .addGap(18, 18, 18)
                .addComponent(signinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(bgWellcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgWellcomeLayout.createSequentialGroup()
                    .addContainerGap(429, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(129, 129, 129)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgWellcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgWellcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinBtnActionPerformed
        // TODO add your handling code here:
       
        
        
        setVisible(false);
        SigninPage Next=new SigninPage();
                Next.setVisible(true);
    }//GEN-LAST:event_signinBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        SignupPage next=new SignupPage();
        dispose();
        next.setVisible(true);
    }//GEN-LAST:event_signupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WellcomingMsg;
    private javax.swing.JPanel bgWellcome;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton signinBtn;
    private javax.swing.JButton signupBtn;
    private javax.swing.JLabel wellcomePic;
    // End of variables declaration//GEN-END:variables
}
